export { z } from 'zod';
export { QueryClientProvider, useQuery, useMutation, useQueryClient } from '@tanstack/react-query';

export { ENDPOINTS } from './api/constants';
export {
  UserSchema,
  VerifyAuthRequestSchema,
  VerifyAuthResponseSchema,
  UpdateUserRequestSchema,
  UpdateUserResponseSchema,
  AvailableServiceSchema,
  ConnectorsAllResponseSchema,
  type User,
  type VerifyAuthRequest,
  type VerifyAuthResponse,
  type UpdateUserRequest,
  type UpdateUserResponse,
  type AvailableService,
  type ConnectorsAllResponse,
  ApexTaskSchema,
  ApexTasksResponseSchema,
  type ApexTask,
  type SubmitApexTaskRequest,
  WahaGetGroupsSchema,
  WahaUpdateModerationRequestSchema,
  WahaUpdateModerationResponseSchema,
  type WahaGetGroupsResponse,
  type WahaChatItem,
  type WahaUpdateModerationRequest,
  type WahaUpdateModerationResponse,
  SuggestionSchema,
  SuggestionsResponseSchema,
  DeleteSuggestionResponseSchema,
  type Suggestion,
  type SuggestionsResponse,
  type DeleteSuggestionResponse,
} from './schemas';
export { ApiClient, initApiClient, getApiClient, ApiError, ValidationError } from './api/apiClient';
export type { ApiClientConfig } from './api/apiClient';

export { createTokenStorage, TOKEN_KEY, type TokenStorage, delayAndExecute } from './utils';
export { stateStorage } from './storage';
export {
  useIsAuthenticated,
  useIsAuthLoading,
  useAuthActions,
  authStore,
  useWahaStore,
  wahaStore,
  useIsWahaConnected,
  useWahaLinkCode,
} from './stores';

export {
  queryClient,
  useVerifyGoogleAuth,
  useUser,
  useUpdateUser,
  USER_QUERY_KEY,
  useGoogleAuthFlow,
  useConnectors,
  useConnectConnector,
  useDisconnectConnector,
  CONNECTORS_QUERY_KEY,
  useApexTasks,
  useSubmitApexTask,
  APEX_TASKS_QUERY_KEY,
  FileSizeError,
  useWahaConnect,
  useWahaDisconnect,
  useWahaLinkPolling,
  useWahaGroups,
  useWahaSyncChats,
  useUpdateWahaGroups,
  WAHA_QUERY_KEY,
  WAHA_GROUPS_KEY,
  useRules,
  useChatRules,
  useCreateRule,
  useUpdateRule,
  useDeleteRule,
  RULES_QUERY_KEY,
  CHAT_RULES_QUERY_KEY,
  useLogout,
  useDeleteAccount,
  useSuggestions,
  useDeleteSuggestion,
  SUGGESTIONS_QUERY_KEY,
} from './query-client';
